### PR TITLE
distribute Synthizer as a multi-file package for proper typing support

### PR DESCRIPTION
**Pull request by Timtam**
…pports proper typing distribution as well

I hopefully forwarded all important objects/functions within the __init__.py/pyi file

I mainly want to use this for testing purpose and will test against the wheels generated by CI.

This is for issue: #13.

I have read CONTRIBUTING.md, am the sole contributor to this pull request, and license my contributions under the Unlicense.

### CODE REVIEW

**Comment by Timtam** [comment]
PR should be ready now if I didn't miss anything. No breakages so far, I can just install the new wheel and everything should continue working as expected (at least it does on my end). I also tested if mypy is now able to properly type-check from an already existing project that wasn't able to typecheck synthizer earlier - that's working now too.

**Comment by ahicks92** [comment]
Did you actually check that typing works, not just that the files are present?  I assume so, but still need to ask.

The __init__.pyi which imports other things seems kinda odd, but I'll take your word that it's right.  I wish we could just put it in the cython and be done...

Also maybe put a little more thought into PR titles/commit messages.  Not going to block on that but I just edited this one and will likely also edit the commit message further when merging.

**Comment by Timtam** [comment]
> Did you actually check that typing works, not just that the files are present? I assume so, but still need to ask.

Yep. I replaced the current 0.12.2 with the wheel built by this PR and ran the typecheck on my pyAGE project. I made sure that it could finally check types by accessing a property the wrong way and it told me to correct the bug, so it finds the types and complains properly.

> The **init**.pyi which imports other things seems kinda odd, but I'll take your word that it's right. I wish we could just put it in the cython and be done...

I pushed a second commit that should have replaced that one with just a `from .synthizer import *` line, didn't this come through?

> Also maybe put a little more thought into PR titles/commit messages. Not going to block on that but I just edited this one and will likely also edit the commit message further when merging.

I usually try to explain the reason behind my changes within my commit messages and am pretty sure that I just did so here too. I however dislike the way GitHub handles long texts too, will make sure to edit properly next time.

**Comment by ahicks92** [comment]
I'm talking about the `__init__.pyi` which is a copy of `__init__.py` pretty much.  It's fine, as long as we know this works.

Going to merge.  Not going to make a big thing about commit messages, but I do rebase merges when I can and that preserves your actual commit history as pushed to the pr.  Don't think i can in this case and given that git rebase is something that people tend to run screaming from I don't generally require that but it's nice when I can get really clean history.

**Pull request merged**
